# Copyright : Whizhack Technologies, India

version: '2.3'

networks:
  ddospot_local:

volumes:
  analytics_data:

services:

  ddospot:
    image: "${REGISTRY_SERVER}/ddospot_xdr_trace_honeypots:prod_amd64_1.8.0"
    container_name: ddospot
    restart: always
    networks:
     - ddospot_local
    ports:
     - "19:19/udp"
     - "53:53/udp"
     - "123:123/udp"
     - "161:161/udp"
     - "1900:1900/udp"
    read_only: true
    volumes:
     - /data/ddospot/log:/opt/ddospot/ddospot/logs
     - /data/ddospot/bl:/opt/ddospot/ddospot/bl
     - /data/ddospot/db:/opt/ddospot/ddospot/db

#=========================
# Analytics
#=========================
  analytics_init:
    image: ${REGISTRY_SERVER}/ubuntu_xdr_trace_analytics:prod_amd64_1.8.0
    command: bash -c "mkdir -p /var/log/zerohack/{photon,gluon,suricata,fatt,p0f,snort,maltrai,listener} && mkdir -p /var/log/zerohack/parted_data/{honeynet,dpi,listener,ids} && mkdir /var/log/zerohack/merger && mkdir -p /var/log/zerohack/normalized_data/{honeynet,dpi,listener,ids} && mkdir /var/log/zerohack/processed_data && mkdir -p /var/log/zerohack/photon/storage/artifacts/http && mkdir -p /var/log/zerohack/photon/storage/rules"
    volumes:
      - analytics_data:/var/log/zerohack

  fatt:
    container_name: fatt
    image: "${REGISTRY_SERVER}/fatt_xdr_trace_analytics:prod_amd64_1.8.0"
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - analytics_data:/var/log/zerohack

  p0f:
    container_name: p0f
    image: "${REGISTRY_SERVER}/p0f_xdr_trace_analytics:prod_amd64_1.8.0"
    restart: always
    network_mode: "host"
    read_only: true
    volumes:
      - analytics_data:/var/log/zerohack

  suricata:
    container_name: suricata
    image: "${REGISTRY_SERVER}/ids_xdr_trace_analytics:prod_amd64_1.8.0"
    restart: always
    environment:
     - OINKCODE=OPEN
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - analytics_data:/var/log/zerohack

  photon:
    container_name: photon
    image: ${REGISTRY_SERVER}/photon_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    env_file:
      - /etc/zh-xdr-trace-client/config.env
    volumes:
      - analytics_data:/var/log/zerohack
    depends_on:
      - analytics_init

  gluon_forwarder:
    container_name: gluon_forwarder
    image: ${REGISTRY_SERVER}/forwarder_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    env_file:
      - /etc/zh-xdr-trace-client/config.env
    volumes:
      - /data:/data
      - analytics_data:/var/log/zerohack
    depends_on:
      - analytics_init

  listener:
    container_name: listener
    image: ${REGISTRY_SERVER}/listener_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init
      
  normalizer:
    container_name: normalizer
    image: ${REGISTRY_SERVER}/normalizer_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init

  merger:
    container_name: merger
    image: ${REGISTRY_SERVER}/merger_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init

  data_pipeline:
    container_name: data_pipeline
    image: ${REGISTRY_SERVER}/data_pipeline_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init
