# Copyright : Whizhack Technologies, India

version: '2.3'

networks:
  tanner_local:

volumes:
  analytics_data:

services:

  tanner_redis:
    container_name: tanner_redis
    image: "${REGISTRY_SERVER}/redis_tanner_xdr_trace_honeypots:prod_amd64_1.8.0"
    restart: always
    stop_signal: SIGKILL
    tty: true
    read_only: true
    networks:
     - tanner_local

  tanner_phpox:
    container_name: tanner_phpox
    image: "${REGISTRY_SERVER}/phpox_xdr_trace_honeypots:prod_amd64_1.8.0"
    restart: always
    stop_signal: SIGKILL
    tmpfs:
     - /tmp:uid=2000,gid=2000
    tty: true
    networks:
     - tanner_local
    read_only: true

  tanner_api:
    container_name: tanner_api
    image: "${REGISTRY_SERVER}/tanner_xdr_trace_honeypots:prod_amd64_1.8.0"
    restart: always
    tty: true
    stop_signal: SIGKILL
    read_only: true
    tmpfs:
     - /tmp/tanner:uid=2000,gid=2000
    networks:
     - tanner_local
    volumes:
     - /data/tanner/log:/var/log/tanner
    command: tannerapi 
    depends_on:
     - tanner_redis

  tanner:
    container_name: tanner
    image: "${REGISTRY_SERVER}/tanner_xdr_trace_honeypots:prod_amd64_1.8.0"
    restart: always
    stop_signal: SIGKILL
    read_only: true
    tty: true
    tmpfs:
     - /tmp/tanner:uid=2000,gid=2000
    networks:
     - tanner_local
    volumes:
     - /data/tanner/log:/var/log/tanner
     - /data/tanner/files:/opt/tanner/files
    depends_on:
     - tanner_api
     - tanner_phpox
    command: tanner

  snare:
    container_name: snare
    image: "${REGISTRY_SERVER}/snare_xdr_trace_honeypots:prod_amd64_1.8.0"
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
     - tanner_local
    ports:
     - "80:80"
    depends_on:
     - tanner

#=========================
# Analytics
#=========================
  analytics_init:
    image: ${REGISTRY_SERVER}/ubuntu_xdr_trace_analytics:prod_amd64_1.8.0
    command: bash -c "mkdir -p /var/log/zerohack/{photon,gluon,suricata,fatt,p0f,snort,maltrai,listener} && mkdir -p /var/log/zerohack/parted_data/{honeynet,dpi,listener,ids} && mkdir /var/log/zerohack/merger && mkdir -p /var/log/zerohack/normalized_data/{honeynet,dpi,listener,ids} && mkdir /var/log/zerohack/processed_data && mkdir -p /var/log/zerohack/photon/storage/artifacts/http && mkdir -p /var/log/zerohack/photon/storage/rules"
    volumes:
      - analytics_data:/var/log/zerohack
  fatt:
    container_name: fatt
    image: "${REGISTRY_SERVER}/fatt_xdr_trace_analytics:prod_amd64_1.8.0"
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - analytics_data:/var/log/zerohack

  p0f:
    container_name: p0f
    image: "${REGISTRY_SERVER}/p0f_xdr_trace_analytics:prod_amd64_1.8.0"
    restart: always
    network_mode: "host"
    read_only: true
    volumes:
      - analytics_data:/var/log/zerohack

  suricata:
    container_name: suricata
    image: "${REGISTRY_SERVER}/ids_xdr_trace_analytics:prod_amd64_1.8.0"
    restart: always
    environment:
     - OINKCODE=OPEN
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - analytics_data:/var/log/zerohack

  photon:
    container_name: photon
    image: ${REGISTRY_SERVER}/photon_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    env_file:
      - /etc/zh-xdr-trace-client/config.env
    volumes:
      - analytics_data:/var/log/zerohack
    depends_on:
      - analytics_init

  gluon_forwarder:
    container_name: gluon_forwarder
    image: ${REGISTRY_SERVER}/forwarder_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    env_file:
      - /etc/zh-xdr-trace-client/config.env
    volumes:
      - /data:/data
      - analytics_data:/var/log/zerohack
    depends_on:
      - analytics_init

  listener:
    container_name: listener
    image: ${REGISTRY_SERVER}/listener_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init
      
  normalizer:
    container_name: normalizer
    image: ${REGISTRY_SERVER}/normalizer_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init

  merger:
    container_name: merger
    image: ${REGISTRY_SERVER}/merger_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init

  data_pipeline:
    container_name: data_pipeline
    image: ${REGISTRY_SERVER}/data_pipeline_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init
