# Copyright : Whizhack Technologies, India

version: '2.3'

networks:
  endlessh_local:
  hellpot_local:
  heralding_local:

volumes:
  analytics_data:

services:

  endlessh:
    image: "${REGISTRY_SERVER}/endlessh_xdr_trace_honeypots:stag_amd64_1.8.0"
    container_name: endlessh
    restart: always
    networks:
     - endlessh_local 
    ports:
     - "22:2222"
    read_only: true
    volumes:
     - /data/endlessh/log:/var/log/endlessh

  heralding:
    container_name: heralding
    image: "${REGISTRY_SERVER}/heralding_xdr_trace_honeypots:stag_amd64_1.8.0"
    read_only: true
    restart: always
    tmpfs:
     - /tmp/heralding:uid=2000,gid=2000
    networks:
     - heralding_local
    ports:
     - "110:110"
     - "143:143"
     - "465:465"
     - "993:993"
     - "995:995"
     - "1080:1080"
     - "5432:5432"
     - "5900:5900"
    volumes:
     - /data/heralding/log:/var/log/heralding

  honeytrap:
    container_name: honeytrap
    image: "${REGISTRY_SERVER}/honeytrap_xdr_trace_honeypots:stag_amd64_1.8.0"
    read_only: true
    restart: always
    tmpfs:
     - /tmp/honeytrap:uid=2000,gid=2000
    network_mode: "host"
    cap_add:
     - NET_ADMIN
    volumes:
     - /data/honeytrap/attacks:/opt/honeytrap/var/attacks
     - /data/honeytrap/downloads:/opt/honeytrap/var/downloads
     - /data/honeytrap/log:/opt/honeytrap/var/log

  hellpot:
    container_name: hellpot
    image: "${REGISTRY_SERVER}/hellpot_xdr_trace_honeypots:stag_amd64_1.8.0"
    read_only: true
    restart: always
    networks:
     - hellpot_local
    ports:
     - "80:8080"
    volumes:
     - /data/hellpot/log:/var/log/hellpot

#=========================
# Analytics
#=========================
  analytics_init:
    image: ${REGISTRY_SERVER}/ubuntu_xdr_trace_analytics:stag_amd64_1.8.0
    command: bash -c "mkdir -p /var/log/zerohack/{photon,gluon,suricata,fatt,p0f,snort,maltrai,listener} && mkdir -p /var/log/zerohack/parted_data/{honeynet,dpi,listener,ids} && mkdir /var/log/zerohack/merger && mkdir -p /var/log/zerohack/normalized_data/{honeynet,dpi,listener,ids} && mkdir /var/log/zerohack/processed_data && mkdir -p /var/log/zerohack/photon/storage/artifacts/http && mkdir -p /var/log/zerohack/photon/storage/rules"
    volumes:
      - analytics_data:/var/log/zerohack
  fatt:
    container_name: fatt
    image: "${REGISTRY_SERVER}/fatt_xdr_trace_analytics:stag_amd64_1.8.0"
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - analytics_data:/var/log/zerohack

  p0f:
    container_name: p0f
    image: "${REGISTRY_SERVER}/p0f_xdr_trace_analytics:stag_amd64_1.8.0"
    restart: always
    network_mode: "host"
    read_only: true
    volumes:
      - analytics_data:/var/log/zerohack

  suricata:
    container_name: suricata
    image: "${REGISTRY_SERVER}/ids_xdr_trace_analytics:stag_amd64_1.8.0"
    restart: always
    environment:
     - OINKCODE=OPEN
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - analytics_data:/var/log/zerohack

  photon:
    container_name: photon
    image: ${REGISTRY_SERVER}/photon_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    env_file:
      - /etc/zh-xdr-trace-client/config.env
    volumes:
      - analytics_data:/var/log/zerohack
    depends_on:
      - analytics_init

  gluon_forwarder:
    container_name: gluon_forwarder
    image: ${REGISTRY_SERVER}/forwarder_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    env_file:
      - /etc/zh-xdr-trace-client/config.env
    volumes:
      - /data:/data
      - analytics_data:/var/log/zerohack
    depends_on:
      - analytics_init

  listener:
    container_name: listener
    image: ${REGISTRY_SERVER}/listener_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init
      
  normalizer:
    container_name: normalizer
    image: ${REGISTRY_SERVER}/normalizer_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init

  merger:
    container_name: merger
    image: ${REGISTRY_SERVER}/merger_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init

  data_pipeline:
    container_name: data_pipeline
    image: ${REGISTRY_SERVER}/data_pipeline_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init
