version: "3"

networks:
  dionaea_local:

volumes:
  analytics_data:

services:

  dionaea:
    image: "${REGISTRY_SERVER}/dionaea_xdr_trace_honeypots:stag_amd64_1.8.0"
    stdin_open: true
    tty: true
    restart: always
    networks:
     - dionaea_local
    ports:
     - "20:20"
     - "21:21"
     - "42:42"
     - "69:69/udp"
     - "81:81"
     - "135:135"
     - "443:443"
     - "445:445"
     - "1433:1433"
     - "1723:1723"
     - "1883:1883"
     - "3306:3306"
     - "5060:5060"
     - "5060:5060/udp"
     - "5061:5061"
     - "27017:27017"
    read_only: true
    volumes:
     - /data/dionaea/roots/ftp:/opt/dionaea/var/dionaea/roots/ftp
     - /data/dionaea/roots/tftp:/opt/dionaea/var/dionaea/roots/tftp
     - /data/dionaea/roots/www:/opt/dionaea/var/dionaea/roots/www
     - /data/dionaea/roots/upnp:/opt/dionaea/var/dionaea/roots/upnp
     - /data/dionaea:/opt/dionaea/var/dionaea
     - /data/dionaea/binaries:/opt/dionaea/var/dionaea/binaries
     - /data/dionaea/log:/opt/dionaea/var/log
     - /data/dionaea/rtp:/opt/dionaea/var/dionaea/rtp

#=========================
# Analytics
#=========================
  analytics_init:
    image: ${REGISTRY_SERVER}/ubuntu_xdr_trace_analytics:stag_amd64_1.8.0
    command: bash -c "mkdir -p /var/log/zerohack/{photon,gluon,suricata,fatt,p0f,snort,maltrai,listener} && mkdir -p /var/log/zerohack/parted_data/{honeynet,dpi,listener,ids} && mkdir /var/log/zerohack/merger && mkdir -p /var/log/zerohack/normalized_data/{honeynet,dpi,listener,ids} && mkdir /var/log/zerohack/processed_data && mkdir -p /var/log/zerohack/photon/storage/artifacts/http && mkdir -p /var/log/zerohack/photon/storage/rules"
    volumes:
      - analytics_data:/var/log/zerohack
  fatt:
    container_name: fatt
    image: "${REGISTRY_SERVER}/fatt_xdr_trace_analytics:stag_amd64_1.8.0"
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - analytics_data:/var/log/zerohack

  p0f:
    container_name: p0f
    image: "${REGISTRY_SERVER}/p0f_xdr_trace_analytics:stag_amd64_1.8.0"
    restart: always
    network_mode: "host"
    read_only: true
    volumes:
      - analytics_data:/var/log/zerohack

  suricata:
    container_name: suricata
    image: "${REGISTRY_SERVER}/ids_xdr_trace_analytics:stag_amd64_1.8.0"
    restart: always
    environment:
     - OINKCODE=OPEN
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
      - analytics_data:/var/log/zerohack

  photon:
    container_name: photon
    image: ${REGISTRY_SERVER}/photon_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    env_file:
      - /etc/trace/config.env
    volumes:
      - analytics_data:/var/log/zerohack
    depends_on:
      - analytics_init

  gluon_forwarder:
    container_name: gluon_forwarder
    image: ${REGISTRY_SERVER}/forwarder_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    env_file:
      - /etc/trace/config.env
    volumes:
      - /data:/data
      - analytics_data:/var/log/zerohack
    depends_on:
      - analytics_init

  listener:
    container_name: listener
    image: ${REGISTRY_SERVER}/listener_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/trace/config.env
    depends_on:
      - analytics_init
      
  normalizer:
    container_name: normalizer
    image: ${REGISTRY_SERVER}/normalizer_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/trace/config.env
    depends_on:
      - analytics_init

  merger:
    container_name: merger
    image: ${REGISTRY_SERVER}/merger_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/trace/config.env
    depends_on:
      - analytics_init

  data_pipeline:
    container_name: data_pipeline
    image: ${REGISTRY_SERVER}/data_pipeline_xdr_trace_analytics:stag_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/trace/config.env
    depends_on:
      - analytics_init
