#!/bin/bash

# Stop all services.
systemctl stop xdr-trace-net xdr-trace-monitor xdr-trace-health;
 
# Delete residue backups.
find /data -name '*.backup' -delete; 

# Refresh your credentials.
/usr/local/bin/trace credentialRefresh; 
# Perform a reconfiguration.
/usr/local/bin/trace reset; 

# Load environment variables from config file and restart the services required.
. /etc/zh-xdr-trace-client/config.env;
if [ -z ${monitor_interface+x} ]; then
    echo "TRACE monitor is not configured, skipping monitor reboot.";
    systemctl start xdr-trace-net xdr-trace-health;
else
    echo "TRACE monitor is configured, rebooting all services."
    systemctl start xdr-trace-net xdr-trace-monitor xdr-trace-health;
fi
