#!/bin/bash

# Stop all services.
systemctl stop xdr-trace-net xdr-trace-monitor xdr-trace-health; 
# Delete all system logs.
sudo rm /var/log/*; 

# Perform a full docker cleanup of the system.
/usr/local/bin/trace update_cleanup;

# Perform a full software upgrade of the system.
sudo apt update; 
sudo apt upgrade -y; 
sudo apt autoremove; 
sudo apt clean; 
# Reboot the system.
sudo reboot;


 

 
 
 