version: '3'

services:

  discovery:
    build: .
    image: 279920935932.dkr.ecr.us-east-1.amazonaws.com/discovery_pipeline:production
    network_mode: "host"
    environment:
     -  OPERATING_ENV=onpremise
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    command:
      sh -c 'mkdir -p /var/log/data/processed_data/ && touch /var/log/data/processed_data/network_map.json && python3 main.py'