#!/bin/bash

# Copyright : Whizhack Technologies, India
# Authors : Team Devops

package_installer () {
    pip3 install -r /etc/zh-xdr-hids-manager-client/requirements.txt --upgrade;
}

systemctl_refresh () {
    sudo systemctl daemon-reload &&
    sudo systemctl restart cron;
    systemctl enable xdr-hids-manager;
}

main () {
    package_installer &&
    systemctl_refresh
}

main