version: "3"

services:

  # Building Main Components.
  maltrail:
    image: ${REGISTRY_SERVER}/maltrail_trace:amd64_${VERSION}
    build: ../analytics/maltrail

  suricata:
    image: ${REGISTRY_SERVER}/suricata_trace:amd64_${VERSION}
    build: ../analytics/suricata

  photon:
    image: ${REGISTRY_SERVER}/photon_trace:amd64_${VERSION}
    build: ../analytics/photon

  p0f:
    image: ${REGISTRY_SERVER}/p0f_trace:amd64_${VERSION}
    build: ../analytics/p0f

  fatt:
    image: ${REGISTRY_SERVER}/fatt_trace:amd64_${VERSION}
    build: ../analytics/fatt
  
  gluon_forwarder:
    image: ${REGISTRY_SERVER}/gluon_forwarder_trace:amd64_${VERSION}
    build: ../analytics/gluon_forwarder

   data_pipeline:
    image: ${REGISTRY_SERVER}/data_pipeline_trace:amd64_${VERSION}
    build: ../analytics/data_pipeline
  
   listener:
    image: ${REGISTRY_SERVER}/listener_trace:amd64_${VERSION}
    build: ../analytics/listener
  
   merger:
    image: ${REGISTRY_SERVER}/merger_trace:amd64_${VERSION}
    build: ../analytics/merger

   normalizer:
    image: ${REGISTRY_SERVER}/normalizer_trace:amd64_${VERSION}
    build: ../analytics/normalizer

  # Building research compoenents. (Will be added in next Release)
  #gluon_forwarder_research:
  #  image: ${REGISTRY_SERVER}/gluon_forwarder_trace_research:amd64_${VERSION}
  #  build: ../research/gluon_forwarder

  # Building monitoring components.
  maltrail_monitor:
    image: ${REGISTRY_SERVER}/maltrail_trace_monitor:amd64_${VERSION}
    build: ../monitor/maltrail

  suricata_monitor:
    image: ${REGISTRY_SERVER}/suricata_trace_monitor:amd64_${VERSION}
    build: ../monitor/suricata

  photon_monitor:
    image: ${REGISTRY_SERVER}/photon_trace_monitor:amd64_${VERSION}
    build: ../monitor/photon

  p0f_monitor:
    image: ${REGISTRY_SERVER}/p0f_trace_monitor:amd64_${VERSION}
    build: ../monitor/p0f

  fatt_monitor:
    image: ${REGISTRY_SERVER}/fatt_trace_monitor:amd64_${VERSION}
    build: ../monitor/fatt

  gluon_forwarder_monitor:
    image: ${REGISTRY_SERVER}/gluon_forwarder_trace_monitor:amd64_${VERSION}
    build: ../monitor/gluon_forwarder

   data_pipeline:
    image: ${REGISTRY_SERVER}/data_pipeline_trace_monitor:amd64_${VERSION}
    build: ../monitor/data_pipeline
  
   listener:
    image: ${REGISTRY_SERVER}/listener_trace_monitor:amd64_${VERSION}
    build: ../monitor/listener
  
   merger:
    image: ${REGISTRY_SERVER}/merger_trace_monitor:amd64_${VERSION}
    build: ../monitor/merger

   normalizer:
    image: ${REGISTRY_SERVER}/normalizer_trace_monitor:amd64_${VERSION}
    build: ../monitor/normalizer