# Generated by Django 4.0.4 on 2022-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_init_configs_platform_val_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='init_configs',
            name='platform_val',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='init_configs',
            name='severity_val',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='init_configs',
            name='time_interval_val',
            field=models.IntegerField(null=True),
        ),
    ]
