# Generated by Django 4.0.4 on 2022-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_init_configs_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='init_configs',
            name='platform_val',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
