# Generated by Django 4.0.5 on 2022-11-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_init_configs_severity_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_data',
            name='trace_environment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization_data',
            name='wazuh_environment',
            field=models.BooleanField(default=False),
        ),
    ]
