# Generated by Django 4.0.5 on 2022-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_added_new_fields_in_organization_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='lang_type',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
