# Generated by Django 4.0.5 on 2022-12-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_language_add_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_data',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
