# Generated by Django 4.0.5 on 2022-12-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_api_export_api_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='application_steps',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='applications',
            name='integration_status',
            field=models.BooleanField(default=False),
        ),
    ]
