# Generated by Django 4.0.5 on 2022-12-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_applications_table_new_fields_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='application_descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='application_steps',
            field=models.TextField(blank=True),
        ),
    ]
