# Generated by Django 4.0.5 on 2022-12-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_alter_applications_application_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='application_steps',
            field=models.JSONField(blank=True),
        ),
    ]
