# Generated by Django 4.0.5 on 2022-12-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_page_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_permissions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
