# Generated by Django 4.0.5 on 2023-01-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_alter_page_permissions_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_data',
            old_name='Country_Code',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='country_data',
            old_name='Country_Name',
            new_name='country_name',
        ),
    ]
