# Generated by Django 4.0.5 on 2023-01-13 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_rename_country_code_country_data_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attach_Location',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('fax_number', models.CharField(blank=True, max_length=255)),
                ('gst_id', models.CharField(blank=True, max_length=255)),
                ('gst_image', models.ImageField(upload_to='')),
                ('tan_id', models.CharField(blank=True, max_length=255)),
                ('tan_image', models.ImageField(upload_to='')),
                ('pan_id', models.CharField(blank=True, max_length=255)),
                ('pan_image', models.ImageField(upload_to='')),
                ('cin_id', models.CharField(blank=True, max_length=255)),
                ('cin_image', models.ImageField(upload_to='')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('branchcode', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('pincode', models.IntegerField(null=True)),
                ('customer_types', models.IntegerField(null=True)),
                ('environment_type', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country_id', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.country_data')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.organization_data')),
            ],
            options={
                'db_table': 'organization_location',
            },
        ),
        migrations.AddField(
            model_name='client_data',
            name='location_id',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.attach_location'),
        ),
    ]
