# Generated by Django 4.0.5 on 2023-06-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_attach_location_client_data_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_permissions',
            name='default_page',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_hids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_nids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='location_id',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.attach_location'),
        ),
    ]
