# Generated by Django 4.0.5 on 2023-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_page_permissions_default_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_permissions',
            name='default_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
