# Generated by Django 4.0.5 on 2023-06-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_blacklisted_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklisted_data',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blacklisted_data',
            name='updated_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
