# Generated by Django 4.0.5 on 2023-06-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_blacklisted_data_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_configs',
            name='location_id',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.attach_location'),
        ),
        migrations.AddField(
            model_name='init_configs',
            name='trace_sensor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='init_configs',
            name='time_interval_val',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Agent_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_agent_group', models.CharField(max_length=255)),
                ('attach_agent_network', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_type', models.CharField(max_length=255)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('updation_timestamp', models.DateTimeField(auto_now=True)),
                ('attach_agent_key', models.CharField(max_length=255)),
                ('trace_attach_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('wazuh_attach_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('db_username', models.CharField(blank=True, max_length=255, null=True)),
                ('db_password', models.CharField(blank=True, max_length=255, null=True)),
                ('db_host', models.CharField(blank=True, max_length=255, null=True)),
                ('db_port', models.CharField(blank=True, max_length=255, null=True)),
                ('nids_event_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('nids_alert_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('nids_incident_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('nids_assets_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('nids_nmap_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('nids_global_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('trace_event_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('trace_alert_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('trace_incident_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('trace_global_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('hids_event_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('hids_alert_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('hids_incident_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('hids_assets_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('org_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.attach_location')),
                ('organization_id', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.organization_data')),
            ],
            options={
                'db_table': 'agent_details',
            },
        ),
    ]
