# Generated by Django 4.0.5 on 2023-07-27 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_page_permissions_xdr_live_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated_Api_export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=150)),
                ('api_key_status', models.BooleanField(default=False)),
                ('product_logs_name', models.CharField(blank=True, max_length=150)),
                ('api_type', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(blank=True, max_length=150)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'updated_api_export',
            },
        ),
    ]
