# Generated by Django 4.0.5 on 2023-08-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_updated_api_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='trace_dpi_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
