# Generated by Django 4.0.5 on 2023-08-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_agent_data_trace_dpi_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='soar_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_soar',
            field=models.BooleanField(default=False),
        ),
    ]
