# Generated by Django 4.0.5 on 2023-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_agent_data_soar_agent_page_permissions_env_soar'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_permissions',
            name='env_ess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_hc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_mm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_sbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_tps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_tptf',
            field=models.BooleanField(default=False),
        ),
    ]
