# Generated by Django 4.0.5 on 2023-09-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_page_permissions_env_ess_page_permissions_env_hc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='ess_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='hc_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='mm_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='sbs_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='tps_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='tptf_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
