# Generated by Django 4.0.5 on 2023-09-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_agent_data_ess_agent_agent_data_hc_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_configs',
            name='sensor_alert_admin',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='init_configs',
            name='sensor_alert_client',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
