# Generated by Django 4.0.5 on 2023-09-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_init_configs_sensor_alert_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_data',
            name='organization_id',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.organization_data'),
        ),
    ]
