# Generated by Django 4.0.5 on 2023-09-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_alter_client_data_organization_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated_Plan_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=150)),
                ('plan_descriptions', models.CharField(blank=True, max_length=150)),
                ('plan_start_date', models.CharField(blank=True, max_length=150)),
                ('plan_end_date', models.CharField(blank=True, max_length=150)),
                ('plan_creations_timestamp', models.CharField(blank=True, max_length=150)),
                ('plan_updations_timestamp', models.CharField(blank=True, max_length=150)),
                ('plan_status', models.BooleanField(default=True)),
                ('plan_key', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'updated_plan_details',
            },
        ),
        migrations.AddField(
            model_name='attach_location',
            name='deactivated_plan_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent_data',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='attach_location',
            name='activated_plan_id',
            field=models.ForeignKey(blank=True, db_column='activated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='init_configs',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.updated_plan_details'),
        ),
    ]
