# Generated by Django 4.0.5 on 2023-09-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_updated_plan_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklisted_data',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.updated_plan_details'),
        ),
    ]
