# Generated by Django 4.0.5 on 2023-10-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_blacklisted_data_updated_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soar_License_Management',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('control_server_domain', models.CharField(blank=True, max_length=250)),
                ('aggregator_domain', models.CharField(blank=True, max_length=250)),
                ('aggregator_port', models.CharField(blank=True, max_length=250)),
                ('sensor_type', models.CharField(blank=True, max_length=250)),
                ('registry_address', models.CharField(blank=True, max_length=250)),
                ('sensor_key', models.CharField(blank=True, max_length=250)),
                ('access_id', models.CharField(blank=True, max_length=250)),
                ('access_key', models.CharField(blank=True, max_length=250)),
                ('edition', models.CharField(blank=True, max_length=250)),
                ('company_index_name', models.CharField(blank=True, max_length=250)),
                ('aws_default_region', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('client_city', models.CharField(blank=True, max_length=250)),
                ('client_latitude', models.CharField(blank=True, max_length=250)),
                ('client_longitude', models.CharField(blank=True, max_length=250)),
                ('client_country_code', models.CharField(blank=True, max_length=250)),
                ('client_country_name', models.CharField(blank=True, max_length=250)),
                ('xdr_soar_status', models.CharField(blank=True, max_length=250)),
                ('soar_sensor_host_url', models.CharField(blank=True, max_length=250)),
                ('backend_port', models.CharField(blank=True, max_length=250)),
                ('frontend_port', models.CharField(blank=True, max_length=250)),
                ('frontend_port_https', models.CharField(blank=True, max_length=250)),
                ('shuffle_default_username', models.CharField(blank=True, max_length=250)),
                ('shuffle_default_password', models.CharField(blank=True, max_length=250)),
                ('shuffle_default_apikey', models.CharField(blank=True, max_length=250)),
                ('license_start_date', models.CharField(blank=True, max_length=250)),
                ('license_end_date', models.CharField(blank=True, max_length=250)),
                ('operating_env', models.CharField(blank=True, max_length=250)),
                ('created_at', models.CharField(blank=True, max_length=250)),
                ('updated_at', models.CharField(blank=True, max_length=250)),
                ('sensor_create_count', models.CharField(blank=True, max_length=150)),
                ('sensor_active_count', models.CharField(blank=True, max_length=150)),
                ('updated_plan_id', models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.updated_plan_details')),
            ],
            options={
                'db_table': 'soar_license_management',
            },
        ),
    ]
