# Generated by Django 4.0.5 on 2023-10-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_soar_license_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_configs',
            name='ransomware_noti_epoch_val',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
