# Generated by Django 4.0.5 on 2023-10-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0040_init_configs_ransomware_noti_epoch_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_configs',
            name='ransomware_noti_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
