# Generated by Django 4.0.5 on 2024-01-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0042_reportschedulertimeformat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_data',
            name='updation_timestamp',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
