version: '3.5'

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  data:

services:
  init:
    image: ubuntu
    container_name: ubuntu
    command: bash -c "mkdir -p /var/log/data/normalized_data/wazuh && mkdir /var/log/data/processed_data"
    volumes:
      - data:/var/log/data

  manager:
    build: 
      context: ./docker/wazuh-manager/.
      dockerfile: Dockerfile
    #image: "406116439221.dkr.ecr.us-east-2.amazonaws.com/manager_xdr_hids:dev_amd64_1.8.0"
    container_name: manager
    restart: always
    ports:
    - 1514:1514
    - 1515:1515
    volumes:
      - /opt/wazuh_manager/wazuh_api_configuration:/var/ossec/api/configuration
      - /opt/wazuh_manager/wazuh_etc:/var/ossec/etc
      - /opt/wazuh_manager/wazuh_logs:/var/ossec/logs
      - /opt/wazuh_manager/wazuh_queue:/var/ossec/queue
      - /opt/wazuh_manager/wazuh_var_multigroups:/var/ossec/var/multigroups
      - /opt/wazuh_manager/wazuh_integrations:/var/ossec/integrations
      - /opt/wazuh_manager/wazuh_active_response:/var/ossec/active-response/bin
      - /opt/wazuh_manager/wazuh_agentless:/var/ossec/agentless
      - /opt/wazuh_manager/wazuh_wodles:/var/ossec/wodles
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
    env_file:
      - /etc/zh-xdr-hids-manager-client/config.env

  forwarder:
    build: 
      context: ./docker/forwarder/.
      dockerfile: Dockerfile
    #image: "406116439221.dkr.ecr.us-east-2.amazonaws.com/forwarder_xdr_hids:dev_amd64_1.8.0"
    container_name: forwarder
    restart: always
    volumes:
      - data:/var/log/data
      - /opt/wazuh_manager/wazuh_logs:/var/ossec/logs
    env_file:
     - /etc/zh-xdr-hids-manager-client/config.env

  normalizer:
    build: 
      context: ./docker/normalizer/.
      dockerfile: Dockerfile
    #image: "406116439221.dkr.ecr.us-east-2.amazonaws.com/normalizer_xdr_hids:dev_amd64_1.8.0"
    container_name: normalizer
    restart: always
    volumes: 
      - data:/var/log/data
    env_file:
      - /etc/zh-xdr-hids-manager-client/config.env
  
  data_pipeline:
    build: 
      context: ./docker/data_pipeline/.
      dockerfile: Dockerfile
    #image: "406116439221.dkr.ecr.us-east-2.amazonaws.com/data_pipeline_xdr_hids:dev_amd64_1.8.0"
    container_name: data_pipeline
    restart: always
    volumes:
      - data:/var/log/data      
    env_file:
      - /etc/zh-xdr-hids-manager-client/config.env    

  
      
    


