#!/bin/bash

# Copyright : Whizhack Technologies, India
# Authors : Team Devops

#Installing pip3 requirements from requirements.txt file
package_installer () {
    pip3 install -r /etc/zh-xdr-trace-client/requirements.txt --upgrade;
}


ipv6_enabler () {
	sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 &&
	sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0 &&
	sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0;
}

certificate_validator() {
    sudo update-ca-certificates;
}

systemctl_refresh () {
    sudo systemctl daemon-reload &&
    sudo systemctl restart cron;
    systemctl enable fail2ban;
}

main () {
    package_installer &&
    ipv6_enabler &&
    certificate_validator &&
    systemctl_refresh;
}

main