version: "3.3"

services:

  riotpot:
    build:
      context: ..
      dockerfile: ./build/docker/Dockerfile
    image: riotpot:development
    #command: 
    restart: always
    ports:
      # Ports under 60 might see errors when unquoted
      # https://stackoverflow.com/questions/58810789/quotes-on-docker-compose-yml-ports-make-any-difference
      - "7:7"
      - "22222:22"
      - "23:23"
      - "502:502"
      - "80:8080"
      - "1883:1883"
      - "5683:5683"
    env_file:
    - ../build/env/.env

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
