# Generated by Django 4.0.4 on 2022-08-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='attach_agent_network',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
