# Generated by Django 4.0.4 on 2022-09-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_agent_data_attach_agent_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_data',
            name='organization_id',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.organization_data'),
        )
    ]
