# Generated by Django 4.0.4 on 2022-09-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_applications'),
    ]

    operations = [        
        migrations.CreateModel(
            name='Init_Configs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(blank=True, max_length=150)),
                ('email_ids', models.CharField(blank=True, max_length=150)),
                ('email_name', models.CharField(blank=True, max_length=100)),
                ('platform_name', models.CharField(blank=True, max_length=50)),
                ('platform_val', models.CharField(blank=True, max_length=50, null=True)),
                ('severity_name', models.CharField(blank=True, max_length=100)),
                ('severity_val', models.IntegerField(null=True)),
                ('accuracy_name', models.CharField(blank=True, max_length=255)),
                ('accuracy_val', models.IntegerField(null=True)),
                ('time_interval_name', models.CharField(blank=True, max_length=255)),
                ('time_interval_val', models.IntegerField(null=True)),
                ('default_config', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.organization_data')),
            ],
            options={
                'db_table': 'init_config',
            },
        ),
    ]
