# Generated by Django 4.0.4 on 2022-09-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_init_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_export',
            name='application_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.applications'),
        )
    ]
