# Generated by Django 4.0.4 on 2022-11-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_severity_val_char_init_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_data',
            name='trace_environment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization_data',
            name='wazuh_environment',
            field=models.BooleanField(default=False),
        )
    ]
