# Generated by Django 4.0.4 on 2022-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_remove_apilogs_org_id_remove_client_data_mfa_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='trace_attach_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='wazuh_attach_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
