# Generated by Django 4.0.4 on 2022-12-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_added_fields_to_agent_details_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='lang_type',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
