# Generated by Django 4.0.4 on 2022-12-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_add_new_col_lang_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_data',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
