# Generated by Django 4.0.4 on 2022-12-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_add_new_col_in_org_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_export',
            name='api_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
