# Generated by Django 4.0.4 on 2022-12-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_new_field_added_to_api_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='application_steps',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='applications',
            name='integration_status',
            field=models.BooleanField(default=False),
        ),
    ]
