# Generated by Django 4.0.4 on 2022-12-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_applications_table_added_new_fields_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='application_descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='application_steps',
            field=models.TextField(blank=True),
        )
    ]
