# Generated by Django 4.0.4 on 2022-12-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0014_applications_table_changed_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='application_steps',
            field=models.JSONField(blank=True),
        )
    ]
