# Generated by Django 4.0.4 on 2023-01-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_page_permission_id_updated_autofiled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attach_Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('phone_number', models.IntegerField(null=True)),
                ('fax_number', models.IntegerField(null=True)),
                ('gst_id', models.CharField(blank=True, max_length=255)),
                ('gst_image', models.ImageField(upload_to='')),
                ('tan_id', models.CharField(blank=True, max_length=255)),
                ('tan_image', models.ImageField(upload_to='')),
                ('pan_id', models.CharField(blank=True, max_length=255)),
                ('pan_image', models.ImageField(upload_to='')),
                ('cin_id', models.CharField(blank=True, max_length=255)),
                ('cin_image', models.ImageField(upload_to='')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('branchcode', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('pincode', models.IntegerField(null=True)),
                ('customer_types', models.IntegerField(null=True)),
                ('environment_type', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_id', models.ForeignKey(blank=True, db_column='billing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.billings_data')),
                ('country_id', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.country_data')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.organization_data')),
                ('plan_id', models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.plans_data')),
                ('timezone_id', models.ForeignKey(blank=True, db_column='timezone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.time_zone_data')),
            ],
            options={
                'db_table': 'organization_location',
            },
        ),
    ]
