# Generated by Django 4.0.4 on 2023-01-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0018_new_table_added_org_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='db_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='org_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.attach_location'),
        ),
    ]
