# Generated by Django 4.0.5 on 2023-01-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0019_updated_agent_details_add_db_user_db_password_org_location'),
    ]

    operations = [
        
    ]
