# Generated by Django 4.0.5 on 2023-01-11 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0020_first_migration_after_db_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='location_id',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.attach_location'),
        ),
        migrations.AlterField(
            model_name='attach_location',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
