# Generated by Django 4.0.5 on 2023-01-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0022_updated_field_type_in_location_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_data',
            old_name='Country_Code',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='country_data',
            old_name='Country_Name',
            new_name='country_name',
        ),
    ]
