# Generated by Django 4.0.5 on 2023-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0023_rename_country_code_country_data_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='application_image',
            field=models.ImageField(blank=True, upload_to=''),
        )
    ]
