# Generated by Django 4.0.5 on 2023-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0024_app_image_field_modified'),
    ]
