# Generated by Django 4.0.5 on 2023-05-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0026_added_new_fields_in_agent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_configs',
            name='location_id',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.attach_location'),
        )
    ]
