# Generated by Django 4.0.4 on 2023-05-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_added_location_fkey_in_init_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_permissions',
            name='env_hids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_nids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='location_id',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.attach_location'),
        ),
    ]
