# Generated by Django 4.0.4 on 2023-05-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0028_added_page_permission_hids_env_nids_end_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='attach_location',
            name='default_page',
            field=models.IntegerField(null=True),
        ),
        
    ]
