# Generated by Django 4.0.4 on 2023-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0029_added_location_models_default_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_permissions',
            name='default_page',
            field=models.IntegerField(null=True),
        ),
    ]
