# Generated by Django 4.0.4 on 2023-06-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0030_added_page_permissions_default_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='is_active',
            field=models.BooleanField(default=False),
        )
    ]
