# Generated by Django 4.0.4 on 2023-06-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0031_added_is_active_column_agent_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='init_configs',
            name='time_interval_val',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
