# Generated by Django 4.0.5 on 2023-06-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0033_org_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_permissions',
            name='default_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
