# Generated by Django 4.0.5 on 2023-06-08 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0034_page_permission_table_default_page_data_type_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklisted_data',
            fields=[
                ('blacklisted_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('blacklisted_class', models.CharField(blank=True, max_length=255, null=True)),
                ('blacklisted_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.attach_location')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.organization_data')),
            ],
            options={
                'db_table': 'blacklisted_details',
            },
        ),
    ]
