# Generated by Django 4.0.4 on 2023-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0035_blacklisted_table_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklisted_data',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blacklisted_data',
            name='updated_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
