# Generated by Django 4.0.4 on 2023-06-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0036_create_at_and_updated_at_added_columns_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklisted_data',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.client_data'),
        ),
    ]
