# Generated by Django 4.0.4 on 2023-06-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0037_user_id_column_blacklised_models_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_permissions',
            name='xdr_live_map',
            field=models.BooleanField(default=False),
        ),
    ]
