# Generated by Django 4.0.4 on 2023-07-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0038_xdr_live_map_column_added_page_permission_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated_Api_export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=150)),
                ('api_key_status', models.BooleanField(default=False)),
                ('product_logs_name', models.CharField(blank=True, max_length=150)),
                ('api_type', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(blank=True, max_length=150)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.client_data')),
            ],
            options={
                'db_table': 'updated_api_export',
            },
        ),
    ]
