# Generated by Django 4.0.4 on 2023-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0039_updated_api_axport_models_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='trace_dpi_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
