# Generated by Django 4.0.4 on 2023-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0041_trace_nids_hids_soar_license_management_Added'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='soar_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_soar',
            field=models.BooleanField(default=False),
        )
    ]
