# Generated by Django 4.0.4 on 2023-08-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0042_added_soar_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='ess_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='hc_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='mm_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='sbs_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='tps_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='tptf_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_ess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_hc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_mm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_sbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_tps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='env_tptf',
            field=models.BooleanField(default=False),
        ),
    ]
