# Generated by Django 4.0.4 on 2023-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0043_added_new_products_in_page_permission_and_agent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_configs',
            name='sensor_alert_admin',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='init_configs',
            name='sensor_alert_client',
            field=models.EmailField(blank=True, max_length=255, null=True),
        )
    ]
