# Generated by Django 4.0.4 on 2023-09-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0044_added_sensor_alert_admin_client_in_init_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated_Plan_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=150)),
                ('plan_descriptions', models.CharField(blank=True, max_length=150)),
                ('plan_start_date', models.CharField(blank=True, max_length=150)),
                ('plan_end_date', models.CharField(blank=True, max_length=150)),
                ('plan_creations_timestamp', models.CharField(blank=True, max_length=150)),
                ('plan_updations_timestamp', models.CharField(blank=True, max_length=150)),
                ('plan_status', models.BooleanField(default=True)),
                ('plan_key', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'updated_plan_details',
            },
        ),
        migrations.RenameField(
            model_name='hids_license_management',
            old_name='preferred_int',
            new_name='current_sensor_status',
        ),
        migrations.RenameField(
            model_name='hids_license_management',
            old_name='sensor_access_id',
            new_name='sensor_count',
        ),
        migrations.RenameField(
            model_name='hids_license_management',
            old_name='sensor_password',
            new_name='sensor_key',
        ),
        migrations.RenameField(
            model_name='nids_license_management',
            old_name='preferred_int',
            new_name='current_sensor_status',
        ),
        migrations.RenameField(
            model_name='nids_license_management',
            old_name='sensor_access_id',
            new_name='sensor_count',
        ),
        migrations.RenameField(
            model_name='nids_license_management',
            old_name='sensor_password',
            new_name='sensor_key',
        ),
        migrations.RenameField(
            model_name='soar_details',
            old_name='sensor_access_id',
            new_name='current_sensor_status',
        ),
        migrations.RenameField(
            model_name='trace_license_management',
            old_name='enable_monitoring',
            new_name='operating_env',
        ),
        migrations.RenameField(
            model_name='trace_license_management',
            old_name='honeynet_interface',
            new_name='sensor_count',
        ),
        migrations.RenameField(
            model_name='trace_license_management',
            old_name='monitor_interface',
            new_name='sensor_create_count',
        ),
        migrations.RenameField(
            model_name='trace_license_management',
            old_name='sensor_access_id',
            new_name='sensor_key',
        ),
        migrations.AddField(
            model_name='attach_location',
            name='deactivated_plan_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hids_license_management',
            name='hids_sensor_active_count',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hids_license_management',
            name='hids_sensor_create_count',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='nids_license_management',
            name='nids_sensor_active_count',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='nids_license_management',
            name='nids_sensor_create_count',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='soar_details',
            name='sensor_count',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='soar_details',
            name='sensor_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='soar_details',
            name='soar_sensor_active_count',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='soar_details',
            name='soar_sensor_create_count',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='soar_details',
            name='soar_sensor_db_host',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='soar_details',
            name='soar_sensor_db_pass',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='soar_details',
            name='soar_sensor_db_port',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='soar_details',
            name='soar_sensor_db_uname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='trace_license_management',
            name='trace_sensor_active_count',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trace_license_management',
            name='trace_sensor_create_count',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agent_data',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='attach_location',
            name='activated_plan_id',
            field=models.ForeignKey(blank=True, db_column='activated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='hids_license_management',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='init_configs',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='nids_license_management',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='page_permissions',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='soar_details',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        ),
        migrations.AddField(
            model_name='trace_license_management',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        ),
    ]
