# Generated by Django 4.0.4 on 2023-09-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0045_updated_plan_details_and_more'),
    ]

    operations = [
    ]
