# Generated by Django 4.0.4 on 2023-09-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0046_remove_apilogs_org_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklisted_data',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        )
    ]
