# Generated by Django 4.0.4 on 2023-09-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0047_added_plan_id_in_blacklisted_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soar_License_Management',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('control_server_domain', models.CharField(blank=True, max_length=250)),
                ('control_server_port', models.CharField(blank=True, max_length=250)),
                ('aggregator_domain', models.CharField(blank=True, max_length=250)),
                ('aggregator_port', models.CharField(blank=True, max_length=250)),
                ('sensor_type', models.CharField(blank=True, max_length=250)),
                ('registry_address', models.CharField(blank=True, max_length=250)),
                ('sensor_key', models.CharField(blank=True, max_length=250)),
                ('access_id', models.CharField(blank=True, max_length=250)),
                ('access_key', models.CharField(blank=True, max_length=250)),
                ('edition', models.CharField(blank=True, max_length=250)),
                ('company_index_name', models.CharField(blank=True, max_length=250)),
                ('preferred_int', models.CharField(blank=True, max_length=250)),
                ('aws_default_region', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('client_city', models.CharField(blank=True, max_length=250)),
                ('client_latitude', models.CharField(blank=True, max_length=250)),
                ('client_longitude', models.CharField(blank=True, max_length=250)),
                ('client_country_code', models.CharField(blank=True, max_length=250)),
                ('client_country_name', models.CharField(blank=True, max_length=250)),
                ('xdr_soar_status', models.CharField(blank=True, max_length=250)),
                ('soar_sensor_host_url', models.CharField(blank=True, max_length=250)),
                ('soar_sensor_db_host', models.CharField(blank=True, max_length=250)),
                ('soar_sensor_db_port', models.CharField(blank=True, max_length=250)),
                ('soar_sensor_db_uname', models.CharField(blank=True, max_length=250)),
                ('soar_sensor_db_pass', models.CharField(blank=True, max_length=250)),
                ('current_sensor_status', models.CharField(blank=True, max_length=250)),
                ('license_start_date', models.CharField(blank=True, max_length=250)),
                ('license_end_date', models.CharField(blank=True, max_length=250)),
                ('operating_env', models.CharField(blank=True, max_length=250)),
                ('data_sharing_mode', models.CharField(blank=True, max_length=250)),
                ('created_at', models.CharField(blank=True, max_length=250)),
                ('updated_at', models.CharField(blank=True, max_length=250)),
                ('sensor_create_count', models.CharField(blank=True, max_length=150)),
                ('sensor_active_count', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'soar_license_management',
            },
        ),
        migrations.RenameField(
            model_name='hids_license_management',
            old_name='hids_sensor_active_count',
            new_name='sensor_active_count',
        ),
        migrations.RenameField(
            model_name='hids_license_management',
            old_name='hids_sensor_create_count',
            new_name='sensor_create_count',
        ),
        migrations.RenameField(
            model_name='nids_license_management',
            old_name='nids_sensor_active_count',
            new_name='sensor_active_count',
        ),
        migrations.RenameField(
            model_name='nids_license_management',
            old_name='nids_sensor_create_count',
            new_name='sensor_create_count',
        ),
        migrations.RenameField(
            model_name='trace_license_management',
            old_name='trace_sensor_active_count',
            new_name='sensor_active_count',
        ),
        migrations.RemoveField(
            model_name='hids_license_management',
            name='current_sensor_status',
        ),
        migrations.RemoveField(
            model_name='hids_license_management',
            name='sensor_count',
        ),
        migrations.RemoveField(
            model_name='nids_license_management',
            name='current_sensor_status',
        ),
        migrations.RemoveField(
            model_name='nids_license_management',
            name='sensor_count',
        ),
        migrations.RemoveField(
            model_name='trace_license_management',
            name='sensor_count',
        ),
        migrations.RemoveField(
            model_name='trace_license_management',
            name='trace_sensor_create_count',
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='default_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_ess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_hc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_hids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_mm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_nids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_sbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_soar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_tps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_tptf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_trace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='env_wazuh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.organization_data'),
        ),
        migrations.AddField(
            model_name='updated_plan_details',
            name='xdr_live_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hids_license_management',
            name='xdr_hids_manager_status',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='nids_license_management',
            name='xdr_nids_status',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='trace_license_management',
            name='diss_status',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='trace_license_management',
            name='sensor_create_count',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='trace_license_management',
            name='xdr_trace_status',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='Soar_Details',
        ),
        migrations.AddField(
            model_name='soar_license_management',
            name='location_id',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.attach_location'),
        ),
        migrations.AddField(
            model_name='soar_license_management',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.organization_data'),
        ),
        migrations.AddField(
            model_name='soar_license_management',
            name='updated_plan_id',
            field=models.ForeignKey(blank=True, db_column='updated_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_app.updated_plan_details'),
        ),
    ]
