# Generated by Django 4.0.4 on 2023-09-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0048_soar_details_table_renamed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace_license_management',
            name='aws_default_region',
            field=models.CharField(max_length=250,blank=True),
        ),
    ]
