# Generated by Django 4.0.4 on 2023-09-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0049_added_aws_default_region_in_trace_license_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hids_license_management',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='hids_license_management',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='nids_license_management',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='nids_license_management',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='soar_license_management',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='soar_license_management',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='trace_license_management',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='trace_license_management',
            name='org_id',
        )
    ]
