# Generated by Django 4.0.4 on 2023-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0050_remove_org_id_and_loc_id_license_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soar_license_management',
            old_name='control_server_port',
            new_name='backend_port',
        ),
        migrations.RenameField(
            model_name='soar_license_management',
            old_name='current_sensor_status',
            new_name='frontend_port',
        ),
        migrations.RenameField(
            model_name='soar_license_management',
            old_name='preferred_int',
            new_name='frontend_port_https',
        ),
        migrations.RenameField(
            model_name='soar_license_management',
            old_name='soar_sensor_db_host',
            new_name='sensor_access_id',
        ),
        migrations.RenameField(
            model_name='soar_license_management',
            old_name='soar_sensor_db_pass',
            new_name='shuffle_default_apikey',
        ),
        migrations.RenameField(
            model_name='soar_license_management',
            old_name='soar_sensor_db_port',
            new_name='shuffle_default_password',
        ),
        migrations.RenameField(
            model_name='soar_license_management',
            old_name='soar_sensor_db_uname',
            new_name='shuffle_default_username',
        ),
    ]
