# Generated by Django 4.0.4 on 2023-10-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0051_updated_soar_license_management_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soar_license_management',
            name='data_sharing_mode',
        ),
    ]
