# Generated by Django 4.0.4 on 2023-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0052_remove_data_sharing_mode_soar_license_management_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soar_license_management',
            name='sensor_access_id',
        ),
    ]
