# Generated by Django 4.0.4 on 2023-10-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0053_remove_sensor_access_id_soar_license_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_configs',
            name='ransomware_noti_epoch_val',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
