# Generated by Django 4.0.4 on 2023-10-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0054_added_ransomware_noti_epoch_val_col_in_init_config_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_configs',
            name='ransomware_noti_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
