---
name: Build and Push Image to AWS ECR
on:
  pull_request_target:
    branches: [ "PW-main" ]
    types: [ "closed" ]
jobs:
 build-and-push:
    if: github.event.pull_request.merged == true
    name: 'Docker build and push to acr'
    runs-on: ubuntu:latest

    defaults:
      run:
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    # login to docker  
    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}
        username: ${{ secrets.ACR_REGISTRY_USERNAME_PW }}
        password: ${{ secrets.ACR_REGISTRY_PASSWORD_PW }}
    - name: Build the image
      id: build-image
      run:
       docker build -t ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}/asset_profiler:0.0.1 docker/asset_profiler/.
 
    - name: push Images to ACR
      run:
        docker push ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}/asset_profiler:0.0.1

     
