
name: Build Hids Manager and Push Images to ECR

on:

  pull_request_target:
    branches: [ "main-rm" ]
    types: [ "closed" ]

jobs:

  build-and-push:

    if: github.event.pull_request.merged == true
    name: SSH and create directory
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
 
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1

      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_RM }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_RM }}
        aws-region: us-east-2
 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
 
    - name: Build doker containers
      run: |
        docker-compose -f ./installers/debian/xdr-hids-manager-client_dev_1.8.0-bullseye_amd64/opt/zh-xdr-hids-manager-client/compose/docker/docker-compose.yml up --build -d

    - name: tag images
      run: |
        docker tag docker_data_pipeline:latest 406116439221.dkr.ecr.us-east-2.amazonaws.com/rishabh_hids_data_pipeline:dev_amd64_1.8.0
        docker tag docker_normalizer:latest 406116439221.dkr.ecr.us-east-2.amazonaws.com/rishabh_hids_normalizer:dev_amd64_1.8.0
        docker tag docker_manager:latest 406116439221.dkr.ecr.us-east-2.amazonaws.com/rishabh_hids_manager:dev_amd64_1.8.0
        docker tag docker_forwarder:latest 406116439221.dkr.ecr.us-east-2.amazonaws.com/rishabh_hids_forwarder:dev_amd64_1.8.0

    - name: push images to ecr
      run: |
        docker push 406116439221.dkr.ecr.us-east-2.amazonaws.com/rishabh_hids_data_pipeline:dev_amd64_1.8.0
        docker push 406116439221.dkr.ecr.us-east-2.amazonaws.com/rishabh_hids_normalizer:dev_amd64_1.8.0
        docker push 406116439221.dkr.ecr.us-east-2.amazonaws.com/rishabh_hids_manager:dev_amd64_1.8.0
        docker push 406116439221.dkr.ecr.us-east-2.amazonaws.com/rishabh_hids_forwarder:dev_amd64_1.8.0

    - name: clean up
      run: |
        docker-compose -f ./installers/debian/xdr-hids-manager-client_dev_1.8.0-bullseye_amd64/opt/zh-xdr-hids-manager-client/compose/docker/docker-compose.yml down


