name: Build and Push Image to AWS ACR
on:
  pull_request_target:
    branches: [ "main-pw" ]
    types: [ "closed" ]
    
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    
    name: Docker build and push to acr
    runs-on: ubuntu-22.04
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # run automation script
    - name: run automate.py 
      working-directory: ./cicd_automation
      run: python automation.py

    # show changes  
    - name: display changes in axios.js
      run: cat src/axios.js
      
      
    # login to docker  
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}
        username: ${{ secrets.ACR_REGISTRY_USERNAME_PW }}
        password: ${{ secrets.ACR_REGISTRY_PASSWORD_PW }}
        
    - name: Build the image
      id: build-image
      run:
       docker build cicd_automation/. -t ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}//xdr_client_frontend:0.0.1a
       docker push ${{ secrets.ACR_ENDPOINTPRT }}/xdr_client_frontend:0.0.1a
