name: Build and Push Image to AWS ECR
on:
  pull_request_target:
    branches: [ "main-pw" ]
    types: [ "closed" ]
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true

    name: SSH and create directory
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: ssh testing phase 1
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          mkdir test1/

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cicd_suricata_testing
        IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
      run: |
        docker build -t cicd_repo .
        docker push 406116439221.dkr.ecr.us-east-1.amazonaws.com/cicd_repo:latest

        docker push ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}/ids:0.1
