#Testin5
name: Build

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  pull_request_target:
    branches: [Debug-test1-RM]
    types: [closed]

jobs:
  # This workflow contains a single job called "build and push"
  build-and-push:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        mkdir ../xdr-hids-manager-client_stag_1.8.0-bullseye_amd64
        cp -TR ./installers/debian/xdr-hids-manager-client_stag_1.8.0-bullseye_amd64/ ../xdr-hids-manager-client_stag_1.8.0-bullseye_amd64
        tar -cvf hids80.tar ../xdr-hids-manager-client_stag_1.8.0-bullseye_amd64/

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAMERM }}
        username: ${{ secrets.USERNAMERM }}
        password: ${{ secrets.PASSWORDRM }}
        port: ${{ secrets.PORT }}
        source: "hids80.tar"
        target: "/home/downloadserver/rishabh"

    - name: ssh and package creation
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTNAMERM }}
        username: ${{ secrets.USERNAMERM }}
        password: ${{ secrets.PASSWORDRM }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          cd rishabh
          tar -xvf hids80.tar
          sudo dpkg-deb --build xdr-hids-manager-client_stag_1.8.0-bullseye_amd64/
