#Testin5
name: Build

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  pull_request_target:
    branches: [main]
    types: [closed]

jobs:
  # This workflow contains a single job called "build and push"
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR ./installers/debian/xdr-trace-client_stag_1.8.0-bullseye_amd64/ ../xdr-trace-client_stag_1.8.0-bullseye_amd64
        tar -cvf deploy.tar ../xdr-trace-client_stag_1.8.0-bullseye_amd64/

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "deploy.tar"
        target: "/home/downloadserver/my_folder"

    - name: ssh and package creation
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          cd my_folder
          tar -xvf deploy.tar

