name: Build and Push Image to AWS ECR
on:
  pull_request_target:
    branches: [ "main-pw" ]
    types: [ "closed" ]
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Azure ACR
      id: login-acr
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}
        username: ${{ secrets.ACR_REGISTRY_USERNAME_PW }}
        password: ${{ secrets.ACR_REGISTRY_PASSWORD_PW }}

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      
      run: |
        docker build -t ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}/ids:0.1 docker/ids/.
        docker push ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}/ids:0.1

