name: Build
on:
  pull_request_target:
    branches: [main]
    types: [closed]

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy File to VM
        run: |
          # Ensure proper file path and correct usage of ssh key
          echo "testing_1"
          echo "testing_2"
          echo "testing_3"
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} docker/* downloadserver@20.231.96.231:
