---
name: Build and Push Image to AWS ECR
on:
  pull_request_target:
    branches: [ "main" ]
    types: [ "closed" ]
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true

    name: SSH and create directory
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0

    - name: Copy File to VM
      run: |
        scp -i ${{ secrets.KEY }} $GITHUB_WORKSPACE/* downloadserver@20.231.96.231:
