#Testin5
name: Build

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  pull_request_target:
    branches: [Debug-test-PW]
    types: [closed]

jobs:
  # This workflow contains a single job called "build and push"
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        mkdir ../xdr-nids-client_prod_1.8.0-bullseye_amd64/
        cp -TR ./installers/debian/xdr-nids-client_prod_1.8.0-bullseye_amd64/ ../xdr-nids-client_prod_1.8.0-bullseye_amd64
        tar -cvf nids30.tar ../xdr-nids-client_prod_1.8.0-bullseye_amd64/

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAMEPW }}
        username: ${{ secrets.USERNAMEPW }}
        key: ${{ secrets.PASSWORDPW }}
        port: ${{ secrets.PORTPW }}
        source: "nids30.tar"
        target: "/home/downloadserver/priyanka"

    - name: ssh and package creation
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTNAMEPW }}
        username: ${{ secrets.USERNAMEPW }}
        key: ${{ secrets.PASSWORDPW }}
        port: ${{ secrets.PORTPW }}
        command_timeout: 30m
        script: | 
          cd priyanka
          tar -xvf nids30.tar
          sudo dpkg-deb --build xdr-nids-client_prod_1.8.0-bullseye_amd64/
