name: Push to ACR on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  push-to-acr:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}
        username: ${{ secrets.ACR_REGISTRY_USERNAME_PW }}
        password: ${{ secrets.ACR_REGISTRY_PASSWORD_PW }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_REGISTRY_LOGIN_SERVER_PW }}/ids:1 .
        docker push ${{ secrets.AZURE_REGISTRY_URL }}/ids:1

