# Copyright : Whizhack Technologies, India

version: '2.3'

volumes:
  monitor_data:
  

services:

#=========================
# Analytics
#=========================
  monitor_init:
    image: ${REGISTRY_SERVER}/ubuntu_xdr_trace_honeypots:prod_amd64_1.8.0
    command: bash -c "mkdir -p /var/log/zerohack/{photon,gluon,suricata,snort,maltrail} && mkdir -p /var/log/zerohack/parted_data/{honeynet,dpi,listener,ids} && mkdir -p /var/log/zerohack/photon/storage/artifacts/http && mkdir -p /var/log/zerohack/photon/storage/rules"
    volumes:
      - monitor_data:/var/log/zerohack
 
  photon_monitor:
    image: ${REGISTRY_SERVER}/photon_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    env_file:
      - /etc/zh-xdr-trace-client/config.env
    volumes:
      - monitor_data:/var/log/zerohack
    depends_on:
      - monitor_init

  gluon_forwarder:
    container_name: gluon_forwarder
    image: ${REGISTRY_SERVER}/forwarder_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    env_file:
      - /etc/zh-xdr-trace-client/config.env
    volumes:
      - /data:/data
      - analytics_data:/var/log/zerohack
    depends_on:
      - analytics_init

  listener:
    container_name: listener
    image: ${REGISTRY_SERVER}/listener_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init
      
  normalizer:
    container_name: normalizer
    image: ${REGISTRY_SERVER}/normalizer_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init

  merger:
    container_name: merger
    image: ${REGISTRY_SERVER}/merger_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init

  data_pipeline:
    container_name: data_pipeline
    image: ${REGISTRY_SERVER}/data_pipeline_xdr_trace_analytics:prod_amd64_1.8.0
    restart: always
    network_mode: "host"
    volumes:
      - analytics_data:/var/log/zerohack
    env_file:
     - /etc/zh-xdr-trace-client/config.env
    depends_on:
      - analytics_init



    
